config/routes.rb
Rails.application.routes.draw do

  root to: "statics#welcome"

  # お問い合わせ
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面

  devise_for :users, controllers: {
  	confirmations: 'confirmations',
  	omniauth_callbacks: "omniauth_callbacks"
  }
  scope module: :user do
    get '/tutorial', to: "tutorials#top"
    get '/tutorial/select_janru', to: "tutorials#select_janru"
    get '/tutorial/select_artist/:janru', to: "tutorials#select_artist", as: "tutorial_select_artist"
    get '/tutorial/select_concert', to: "tutorials#select_concert", as: "tutorial_select_concert_first"
    get '/tutorial/select_concert/:artist_id', to: "tutorials#select_concert", as: "tutorial_select_concert"
    post '/tutorial/finish', to: "tutorials#finish"
    get '/timeline/future', to: "timelines#future"
    get '/timeline/past', to: "timelines#past"
    get '/account', to: "statics#account"
    put '/account', to: "statics#update"
    get '/search', to: "statics#search"
    post '/search/filter', to: "statics#search_filter"
    resource :favorite_artists, only: [:create, :destroy, :show]
    resource :favorite_prefectures, only: [:create, :destroy, :show]
    resource :user_concert_joinings, only: [:create]
    resources :concerts, only: [:create, :new, :update, :edit, :index]
    resource :artists, only: [:create]
    post 'concerts/filter', to: "concerts#filter"
    post 'concerts/check_duplicate', to: "concerts#check_duplicate"
    post 'concerts/add_appearance_artist', to: "concerts#add_appearance_artist"
  end

  get '/:username/joined', to: 'users#joined', as: 'user_joined'
  get '/:username/joining', to: 'users#joining', as: 'user_joining'
  get '/:username/favorite', to: 'users#favorite', as: 'user_favorite'
  #get 'card_images/:username/joining', to: 'card_images#joining', as: 'card_image_joining'
  #get 'card_images/:username/joined', to: 'card_images#joined', as: 'card_image_joined'
  post '/appearance_artists/sort', to: 'appearance_artists#sort'
  resources :artists, only: [:show] do
    resource :concerts, only: [:show] do
      post '/filter', to: 'concerts#filter'
    end
  end
  resources :concerts, only: [:show] do
    resource :tickets, only: [:show]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins, only: [:sessions]
  namespace :admin do
    resources :deactive_concerts
    resources :concerts, only: [:index, :update, :destroy]
    resources :artists, only: [:index, :update, :destroy]
    resources :medium_artist_relations
    resources :artist_relations
    resources :media
    resources :appearance_artists
  end

end

app/views/shared/_appearance_artists.html.slim
- artists_num = appearance_artists.size
- appearance_artists.each.with_index do |appearance_artist, i|
  - if i == 3
    span.label-block.label-thin_base.mr3 = "他#{artists_num-3}アーティスト"
    - break
  span.label-block.label-thin_base.mr3
    = "#{appearance_artist.artist.name}#{'（出演日未定）' if appearance_artist.not_decided}"

app/views/shared/_concert_info.html.slim
.concert-info
  .title-wrap
    span.title.pr5 = concert.try(:title)
    - if concert.category
      - if concert.category < 10
        span.label-block.label-fes.mr3 = "フェス・イベント"
  span.date = jp_date concert.try(:date)
  span.place = "@#{concert.try(:place)}(#{concert.prefecture.try(:name)})"
  .appearance-artists cid = "#{concert.id}"
    - appearance_artists = concert.appearance_artists
    = render "shared/appearance_artists", appearance_artists: appearance_artists

app/views/shared/_future_concert_list.html.slim
.concert-item id = "concert-#{concert.id}"
  = render 'shared/concert_info', concert: concert

  .concert-widget
    span.join class="#{'active' if join_concert_ids.include?(concert.id)}"
      = link_to user_concert_joinings_path(concert_id: concert.id), remote: true, method: :post
        i.fa.fa-check-circle aria-hidden="true"
        |  参加予定
    /span.ticket
      = link_to concert_tickets_path(concert_id: concert.id)
        i.fa.fa-ticket aria-hidden="true"
        |  チケットを探す

app/views/shared/_login_form.html.slim
.form-group
  h3.text-center LiveLogにログイン
  = link_to omniauth_authorize_path(:user, :twitter), class: "btn btn-twitter"
    i.fa.fa-twitter
    span Twitterでログイン

  .mail-login
    p.text-center メールアドレスでログイン
    = simple_form_for(User.new, as: :user, url: session_path(:user)) do |f|
      .form-inputs
        = f.input :email, required: false, autofocus: true, label: false, placeholder: "メールアドレス"
        = f.input :password, required: false, label: false, placeholder: "パスワード"
        = f.hidden_field :remember_me, as: :boolean, value: true
      .form-actions
        = f.button :submit, "ログイン"
  .text-center
    = link_to "アカウントを作成する", new_user_registration_path

app/views/shared/_search_box.html.slim
.search-box
  i.fa.fa-search.fa-lg
  input.string.optional.form-control#artist-search type="text" value="" placeholder="アーティスト名で探す"

app/views/shared/_signin_form.html.slim
.form-group
  h3.text-center = "#{Settings.site.name}にログイン"
  = link_to omniauth_authorize_path(:user, :twitter), class: "btn btn-twitter"
    i.fa.fa-lg.fa-twitter
    span Twitterでログイン

  .mail-login
    p.text-center メールアドレスでログイン
    /= simple_form_for(User.new, as: :user, url: session_path(:user)) do |f|
    = simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
      .form-inputs
        = f.input :email, required: true, label: false, placeholder: "メールアドレス"
        = f.input :password, required: true, label: false, placeholder: "パスワード"
        = f.hidden_field :remember_me, as: :boolean, value: true
      .form-actions
        = f.button :submit, "ログイン"
  .text-center
    = link_to "アカウントを作成する", new_user_registration_path

app/views/shared/_signup_form.html.slim
.form-group
  h3.text-center アカウント作成
  = link_to omniauth_authorize_path(:user, :twitter), class: "btn btn-twitter"
    i.fa.fa-lg.fa-twitter
    span Twitterで登録

  .mail-login
    p.text-center メールアドレスで登録
    = simple_form_for(User.new, as: :user, url: registration_path(:user)) do |f|
      = f.error_notification
      .form-inputs
        = f.input :email, required: true, label: false, placeholder: "メールアドレス"
        = f.input :password, required: true, label: false, placeholder: "パスワード"
        = f.input :password_confirmation, label: false, required: true, placeholder: "パスワード確認用"
      .form-actions
        = f.button :submit, "登録"
  .text-center
    = link_to "ログインする", root_path

app/views/shared/_ticket_list.html.slim
- images = { "ヤフオク" => "site-logo/yahuoku_logo.png", "楽天オークション" => "site-logo/rakuten_logo.png", "モバオク" => "site-logo/mabaoku_logo.png", "チケット流通センター" => "site-logo/tikeryu_logo.gif", "チケットキャンプ" => "site-logo/tikecam_logo.png", "チケットストリート" => "site-logo/tikesuto_logo2.png"}

tr.ticket-item
  td.media
    = link_to root_path, target: "_blank"
      span
        p.media-logo
          = image_tag ticket.medium.logo_path

  td.info
    = link_to root_path, target: "_blank"
      span
        p.seat = ticket.seat
        p.price
          span = "#{number_with_delimiter ticket.price}円"