config/routes.rb
Rails.application.routes.draw do

  root to: "statics#welcome"

  # お問い合わせ
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面

  devise_for :users, controllers: {
  	confirmations: 'confirmations',
  	omniauth_callbacks: "omniauth_callbacks"
  }
  scope module: :user do
    get '/tutorial', to: "tutorials#top"
    get '/tutorial/select_janru', to: "tutorials#select_janru"
    get '/tutorial/select_artist/:janru', to: "tutorials#select_artist", as: "tutorial_select_artist"
    get '/tutorial/select_concert', to: "tutorials#select_concert", as: "tutorial_select_concert_first"
    get '/tutorial/select_concert/:artist_id', to: "tutorials#select_concert", as: "tutorial_select_concert"
    post '/tutorial/finish', to: "tutorials#finish"
    get '/timeline/future', to: "timelines#future"
    get '/timeline/past', to: "timelines#past"
    get '/account', to: "statics#account"
    put '/account', to: "statics#update"
    get '/search', to: "statics#search"
    post '/search/filter', to: "statics#search_filter"
    resource :favorite_artists, only: [:create, :destroy, :show]
    resource :favorite_prefectures, only: [:create, :destroy, :show]
    resource :user_concert_joinings, only: [:create]
    resources :concerts, only: [:create, :new, :update, :edit, :index]
    resource :artists, only: [:create]
    post 'concerts/filter', to: "concerts#filter"
    post 'concerts/check_duplicate', to: "concerts#check_duplicate"
    post 'concerts/add_appearance_artist', to: "concerts#add_appearance_artist"
  end

  get '/:username/joined', to: 'users#joined', as: 'user_joined'
  get '/:username/joining', to: 'users#joining', as: 'user_joining'
  get '/:username/favorite', to: 'users#favorite', as: 'user_favorite'
  #get 'card_images/:username/joining', to: 'card_images#joining', as: 'card_image_joining'
  #get 'card_images/:username/joined', to: 'card_images#joined', as: 'card_image_joined'
  post '/appearance_artists/sort', to: 'appearance_artists#sort'
  resources :artists, only: [:show] do
    resource :concerts, only: [:show] do
      post '/filter', to: 'concerts#filter'
    end
  end
  resources :concerts, only: [:show] do
    resource :tickets, only: [:show]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins, only: [:sessions]
  namespace :admin do
    resources :deactive_concerts
    resources :concerts, only: [:index, :update, :destroy]
    resources :artists, only: [:index, :update, :destroy]
    resources :medium_artist_relations
    resources :artist_relations
    resources :media
    resources :appearance_artists
  end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def welcome
  	redirect_to concerts_path if user_signed_in?
  end
end

app/controllers/user/artists_controller.rb
class User::ArtistsController < User::UserApplicationController

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      @artist.update(creator_id: current_user.id, admin_denied: true)
      render "create.js"
    else
      render "error.js"
    end
  end

  private

    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/controllers/user/concerts_controller.rb
class User::ConcertsController < User::UserApplicationController
  before_action :redirect_favorite_prefecture, only: [:index]
  before_action :set_concert, only: [:update, :edit]
  before_action :set_concert_ids, only: [:index, :filter]
  before_action :set_years, only: [:index, :filter]

  def new
    @concert = Concert.new
    @concert.appearance_artists.build
  end

  def edit
  end

  def index
    @concerts = Concert.includes_for_list.where(id: @concert_ids).order("date DESC").page(params[:page])
    @join_concert_ids = Concert.ids_joined_by(current_user, @concerts)
  end

  def filter
    @concerts = Concert.includes_for_list.where(id: @concert_ids).order("date DESC").page(params[:page])
    @join_concert_ids = user_signed_in? ? Concert.ids_joined_by(current_user, @concerts) : []
    render template: "concerts/filter.js"
  end

  def create
    @concert = Concert.new(concert_params)
    #render text: params[:auto_register] == "1"
    artist_ids = params[:appearance_artist][:artist_id].values
    if @concert.save!
      @concert.update(creator_id: current_user.id)
      artist_ids.each do |aid|
        @concert.appearance_artists.create(artist_id: aid)
      end
      @concert.appearance_artists.update_all(creator_id: current_user.id)
      flash[:info] = "ライブを作成しました"
      redirect_to new_concert_path
    else
      render :new
    end
    if params[:auto_register] == "1"
      @concert.user_concert_joinings.create(user_id: current_user.id)
    end
  end

  def update
    if @concert.update(concert_params)
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def check_duplicate
    date = Date.parse(params[:date_text])
    prefecture_id = params[:prefecture_id].to_i

    concert_ids = Concert.includes(:appearance_artists).
                  where(date: date, appearance_artists: {artist_id: params[:aids]}).pluck(:id)
    @concerts = Concert.includes_for_list.where(id: concert_ids).limit(1)
    @join_concert_ids = user_signed_in? ? Concert.ids_joined_by(current_user, @concerts) : []
    #render "check_duplicate.js"
  end

  def add_appearance_artist
    concert_id = params[:concert_id].to_i
    artist_id = params[:artist_id].to_i
    @appearance_artist = Concert.find(concert_id).appearance_artists.build(artist_id: artist_id)
    if @appearance_artist.save
      @appearance_artist.update(creator_id: current_user.id)
    else
    end
  end

  private

    def set_concert
      @concert = Concert.includes_for_list.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_params
      params.require(:concert).permit(
        :title, :place, :prefecture_id, :date, :eplus_id, :livefans_path, :creator_id
      )
    end

    def artist_params
      params.require(:appearance_artist).permit(:artist_id)
    end

    def redirect_favorite_prefecture
      unless request.url.match(/prefecture_id/)
        if current_user.prefectures.present?
          favorite_prefecture_id = current_user.favorite_prefectures.first.prefecture_id
          redirect_to concerts_path(prefecture_id: favorite_prefecture_id)
        end
      end
    end

    def set_concert_ids
      update_favorite_prefecture(params[:prefecture_id])
      @favorite_artist_ids = current_user.favorite_artists.pluck(:artist_id)
      #@concert_ids = Concert.includes(:prefecture, :appearance_artists).
                    #where(appearance_artists: {artist_id: @favorite_artist_ids}).
                    #order("date").take(200).pluck(:id)

      if params[:year].present?
        @year = params[:year].to_i
        if params[:prefecture_id].present?
          @prefecture_id = params[:prefecture_id]
          @concert_ids = Concert.includes(:prefecture, :appearance_artists).
                         where(appearance_artists: {artist_id: @favorite_artist_ids}, prefecture_id: @prefecture_id).
                         this_year(@year).order("date DESC").take(300).pluck(:id)
        else
          @concert_ids = Concert.includes(:prefecture, :appearance_artists).
                         where(appearance_artists: {artist_id: @favorite_artist_ids}).
                         this_year(@year).order("date DESC").take(300).pluck(:id)
        end
      else
        if params[:prefecture_id].present?
          @prefecture_id = params[:prefecture_id]
          @concert_ids = Concert.includes(:prefecture, :appearance_artists).
                         where(appearance_artists: {artist_id: @favorite_artist_ids}, prefecture_id: @prefecture_id).
                         order("date DESC").take(300).pluck(:id)
        else
          @concert_ids = Concert.includes(:prefecture, :appearance_artists).
                         where(appearance_artists: {artist_id: @favorite_artist_ids}).
                         order("date DESC").take(300).pluck(:id)
        end
      end
    end

    def set_years
      years = [*1996..Date.today.year].reverse
      @years = years.map{|year| ["#{year}年", year]}
    end
end

app/controllers/user/favorite_artists_controller.rb
class User::FavoriteArtistsController < User::UserApplicationController
  # POST /artists
  # POST /artists.json
  def show
    @artists = current_user.artists.includes(:favorite_artists).resources(:favorite_artists)
  end

  def create
    #@favorite_artist = FavoriteArtist.new(artist_id: params[:artist_id], user_id: current_user.id)
    @favorite_artist = FavoriteArtist.find_by(artist_id: params[:artist_id], user_id: current_user.id)
    if @favorite_artist
      @favorite_artist.destroy
      render "destroy.js"
    else
      @favorite_artist = FavoriteArtist.new(artist_id: params[:artist_id], user_id: current_user.id)
      old_recommended_artist_ids = current_user.recommended_artist_ids
      if @favorite_artist.save
        @favorite_counts = current_user.favorite_artists.size
        @favorite_artist_ids = current_user.favorite_artists.pluck(:artist_id)
        new_recommended_artist_ids =
          @favorite_artist.artist.related_artist_ids - old_recommended_artist_ids - @favorite_artist_ids
        @related_artists = Artist.where(id: new_recommended_artist_ids, category: nil)
      else
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @favorite_artist.destroy
  end

end

app/controllers/user/favorite_prefectures_controller.rb
class User::FavoritePrefecturesController < User::UserApplicationController
  before_action :set_favorite_prefecture, only: [:destroy]

  def create
    @favorite_prefecture = current_user.favorite_prefectures.new(favorite_prefecture_params)
    @favorite_prefecture.save
  end

  def destroy
    @favorite_prefecture.destroy
  end

  def show
    @user = current_user
    @favorite_prefectures = @user.favorite_prefectures
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite_prefecture
      @favorite_prefecture = FavoritePrefecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_prefecture_params
      params.require(:favorite_prefecture).permit(:user_id, :prefecture_id)
    end

end

app/controllers/user/statics_controller.rb
class User::StaticsController < User::UserApplicationController
  def account
    @user = current_user
  end

  def update
    #if @inquiry.valid?
    @user = current_user.update(user_params)
    redirect_to account_path, notice: '保存しました'
  end

  def search
    recommended_artist_ids = current_user.recommended_artist_ids
    favorite_artists = current_user.favorite_artists
    @favorite_artist_ids = favorite_artists.pluck(:artist_id)
    recommended_artist_ids -= @favorite_artist_ids
    @recommended_artists = Artist.where(id: recommended_artist_ids.shuffle[1..30])
  end

  def search_filter
    @favorite_artist_ids = current_user.favorite_artists.pluck(:artist_id)
    if params[:input_text].present?
      input_space_deleted = delete_space(params[:input_text])
      match_text = '%'+input_space_deleted+'%'
      @artists = Artist.search_match_artists(match_text).sort_by { |a| a.name.size }
    else
      @artists = nil
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :username_jp, :description, :icon)
  end
end

app/controllers/user/timelines_controller.rb
class User::TimelinesController < User::UserApplicationController
  before_action :set_favorite_artist_ids, only: [:future, :past]

  def future
    prefectures = current_user.prefectures
    if prefectures.present?
      @favorite_prefecture_ids = current_user.prefectures.pluck(:id)
      concert_ids = Concert.includes(:prefecture, :appearance_artists).
                    where(prefecture_id: @favorite_prefecture_ids, appearance_artists: {artist_id: @favorite_artist_ids}).
                    open.order("date").take(200).pluck(:id)
      @concerts = Concert.includes_for_list.where(id: concert_ids).order("date").page(params[:page])
      @join_concert_ids = Concert.ids_joined_by(current_user, @concerts)
    else
      concert_ids = Concert.includes(:prefecture, :appearance_artists).
                    where(appearance_artists: {artist_id: @favorite_artist_ids}).
                    open.order("date").take(200).pluck(:id)

      @concerts = Concert.includes_for_list.where(id: concert_ids).order("date").page(params[:page])
      @join_concert_ids = Concert.ids_joined_by(current_user, @concerts)
    end
  end

  def past
    concert_ids = Concert.includes(:prefecture, :appearance_artists).
                  where(appearance_artists: {artist_id: @favorite_artist_ids}).
                  close.order("date DESC").take(200).pluck(:id)
    @concerts = Concert.includes_for_list.where(id: concert_ids).order("date").page(params[:page])
    @join_concert_ids = Concert.ids_joined_by(current_user, @concerts)
  end

  private

  def set_favorite_artist_ids
    @favorite_artist_ids = current_user.favorite_artists.pluck(:artist_id)
    #@concerts = Concert.includes(:appearance_artists).where(appearance_artists: {artist_id: favorite_artist_ids})
  end
end

app/controllers/user/tutorials_controller.rb
class User::TutorialsController < User::UserApplicationController

  def top
  end

  def select_janru
    redirect_to root_path if current_user.tutorial_finished
  end

  def select_artist
    redirect_to root_path if current_user.tutorial_finished
    @artists = Artist.where(category: params[:janru])
    @favorite_artist_ids = current_user.artists.pluck(:artist_id)
  end

  def select_concert
    redirect_to root_path if current_user.tutorial_finished

    @artist = params[:artist_id] ? Artist.find(params[:artist_id]) : current_user.artists.first
    @concerts = @artist.concerts.close.order("date DESC")
    @years = @concerts.pluck(:date).map{|date| ["#{date.year}年", date.year]}.uniq
    @years ||= []
    @concerts = @concerts.close.includes_for_list.page(params[:page])
    @join_concert_ids = user_signed_in? ? Concert.ids_joined_by(current_user, @concerts) : []
  end

  def finish
    current_user.update(tutorial_finished: true)
    #redirect_to root_path
    redirect_to user_joined_path(current_user.username)
  end
end

app/controllers/user/user_application_controller.rb
class User::UserApplicationController < ApplicationController
  before_action :authenticate_user!
  before_action :finish_tutorial

  def finish_tutorial
    unless current_user.tutorial_finished
      unless controller_name.match(/^tutoria/)
        redirect_to tutorial_path if request.get?
      end
    end
  end
  #layout "user_application"
end

app/controllers/user/user_concert_joinings_controller.rb
class User::UserConcertJoiningsController < User::UserApplicationController
  # POST /artists
  # POST /artists.json
  def create
    @user_concert_joining = UserConcertJoining.find_by(concert_id: params[:concert_id], user_id: current_user.id)
    if @user_concert_joining
      @user_concert_joining.destroy
      render "destroy.js"
    else
      @user_concert_joining = UserConcertJoining.create(concert_id: params[:concert_id], user_id: current_user.id)
      @join_counts = current_user.user_concert_joinings.size
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @favorite_artist.destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def joining
    @concerts = @this_user.concerts.includes_for_list.
                open.order("date").page(params[:page])
    @join_concert_ids = user_signed_in? ? Concert.ids_joined_by(current_user, @concerts) : []
  end

  def joined
    @concerts = @this_user.concerts.close
    @years = @concerts.pluck(:date).sort.reverse.map{|date| ["#{date.year}年", date.year]}.uniq.unshift(["全期間", nil])
    if params[:year].present?
      @year = params[:year].to_i
      @concerts = @concerts.this_year(@year)
    end
    @artist_ids_with_count = @concerts.joins(:appearance_artists).where("category >= 10").
    #@artist_ids_with_count = @concerts.includes(appearance_artists: :artist).
                             #references(appearance_artists: :artist).
                             group("appearance_artists.artist_id").order("count(*) DESC").count.to_a
    @fes_count = @concerts.where("category < 10").size
    @joined_count = @concerts.size
    @concerts = @concerts.includes_for_list.
                order("date DESC").page(params[:page])
    @join_concert_ids = user_signed_in? ? Concert.ids_joined_by(current_user, @concerts) : []
  end

  def favorite
    @artists = @this_user.artists.includes(:favorite_artists).references(:favorite_artists)
    @favorite_artist_ids = user_signed_in? ? current_user.artists.pluck(:artist_id) : []
  end

  private

  def set_user
  	@this_user = User.find_by(username: params[:username])
  end
end

app/views/user/statics/account.html.slim
h1.title アカウント

.content-divider
  p プロフィール編集

.content-container
  .form-group
    = simple_form_for(@user, as: :user, url: account_path, html: { method: :put }) do |f|
      = f.error_notification

      .form-inputs
        = image_tag(current_user.icon_path, size: "73x73")
        = f.input :icon, label: "アイコン画像", input_html: { preview_version: :thumb }
        = f.input :username, required: true, label: "ユーザーID"
        = f.input :username_jp, required: true, label: "ユーザー名"
        = f.input :description, required: true, as: :text, label: "自己紹介"

      .form-actions
        = f.button :submit, "保存", class: "btn btn-info"

app/views/user/statics/profile.html.slim
h1.title アカウント

.content-container
  p = "ユーザーID : #{current_user.username}"

  /p ユーザーIDを変更
   span ※参加履歴と参加ログのURLにつきます

  p.sub-title
    span 都道府県を登録
  p.small 登録した都道府県でのライブ情報のみがタイムラインに表示されるようになります

  table.table.prefecture-seletor
    tbody
      tr
        = simple_form_for(FavoritePrefecture.new, as: :favorite_prefecture, url: favorite_prefectures_path, remote:true) do |f|
          td
            .form-inputs
              = f.input :prefecture_id, :collection => Prefecture.all, selected: 122, label: false
          td
            .form-actions
              = f.button :submit, "登録", class: "btn-warning"

  table#registered-prefectures.table.table-boder
    tbody
      = render partial: "user/favorite_prefectures/add_favorite_prefecture", collection: @favorite_prefectures, :as => "favorite_prefecture"

app/views/user/statics/search.html.slim
.welcome-container
  /.welcome-text
    p.welcome-message.janru アーティストをお気に入りに登録しよう

  .form-group.search
    = render "shared/search_box"
    /.search-box
      i.fa.fa-search.fa-lg
      input.string.optional.form-control#artist-search type="text" value="" placeholder="アーティスト名で探す" autofocus=true
    #search-result-list.artist-list
      table.table.hidden
        tbody

  p.artist-selector-title.text-center あなたにオススメのアーティスト
  #related_artist-list.artist-list
    table.table
      tbody
        = render partial: "user/shared/artist_list", collection: @recommended_artists, :as => "artist"

app/views/user/statics/search_filter.js.slim
| if ($('body.tutorials').length) {
    $('#search-result-list table tbody').empty().append("#{j(render partial: "user/shared/artist_selector", collection: @artists, as: "artist")}");
  }
  else if ($('body.concerts.user').length){
    $('#search-result-list table tbody').empty().append("#{j(render partial: "user/shared/appearance_artist_selector", collection: @artists, as: "artist")}");
  }
  else{
    $('#search-result-list table tbody').empty().append("#{j(render partial: "user/shared/artist_list", collection: @artists, as: "artist")}");
  }

app/views/user/statics/timeline.html.slim
h1 timeline

table.table
  tbody
  - @concerts.each do |concert|
    tr
      td = concert.try(:title)
      td = concert.try(:place)
      td = concert.try(:date)

app/views/user/statics/tutorial.html.slim
.welcome-container
  .welcome-text
    p.welcome-message よく行くライブのジャンルは？

  #janru-list
    .table-row
      #pop.janru_box
        = link_to tutorial_janru_path(2), class: "tabel-link"
          span 邦楽POP
      #rock.janru_box
        = link_to tutorial_janru_path(3), class: "tabel-link"
          span 邦楽ROCK
    .table-row
      #ldh.janru_box
        = link_to tutorial_janru_path(4), class: "tabel-link"
          span LDH
      #idol.janru_box
        = link_to tutorial_janru_path(5), class: "tabel-link"
          span アイドル
    .table-row
      #anime.janru_box
        = link_to tutorial_janru_path(6), class: "tabel-link"
          span アニソン・声優
      #korean.janru_box
        = link_to tutorial_janru_path(7), class: "tabel-link"
          span 韓流

app/views/user/statics/tutorial_janru.html.slim
.welcome-container
  .welcome-text
    p.welcome-message.janru ライブに行きたいアーティストを選ぼう

  .form-group
    input.string.optional.form-control#artist-search type="text" value="" placeholder="アーティスト名で探す"
    #search-result-list.artist-selector
      table.table.hidden
        tbody
           = render partial: "user/shared/artist_selector", collection: Artist.all, :as => "artist"

  p.artist-selector-title あなたにオススメのアーティスト
  #related_artist-list.artist-selector
    table.table.hidden
      tbody
  #artist-list.artist-selector
    table.table
      tbody
        = render partial: "user/shared/artist_selector", collection: @artists, :as => "artist"

#tutorial-notification.hidden
  = link_to "Livelogを始める", tutorial_finish_path, method: :post

app/views/user/statics/tutotial.html.slim
h1 tutorial